Parameters:
  LaunchPrincipal:
    Type: String
    Description: Specify an ARN of a user, group or role to be used for provisioning this product

Resources:

  # Products populated to Service Catalog
  ###################################################  
  
  SageMakerStudioProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Owner: AWS
      Name: SageMaker Studio Domain
      ProvisioningArtifactParameters:
        - Name: v1
          Description: Provisions a SageMaker domain and its associated roles for Studio users
          Info:
            LoadTemplateFromURL: https://studio-provisioning-aggarzo.s3-us-west-2.amazonaws.com/studio_product.template

  SageMakerUserProfileProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Owner: AWS
      Name: SageMaker Studio User Profile
      ProvisioningArtifactParameters:
        - Name: v1
          Description: Provisions a new User Profile under SageMaker Studio
          Info:
            LoadTemplateFromURL: https://studio-provisioning-aggarzo.s3-us-west-2.amazonaws.com/studio_user_profile.template

  SageMakerStudioProductPortfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      ProviderName: AWS
      DisplayName: SageMaker Product Portfolio

  SageMakerStudioProductPortfolioAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref SageMakerStudioProductPortfolio
      ProductId: !Ref SageMakerStudioProduct
  
  SageMakerUserProfileProductPortfolioAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref SageMakerStudioProductPortfolio
      ProductId: !Ref SageMakerUserProfileProduct


# Sets the principal who can initate provisioning from Service Catalog
#######################################################################
  
  SageMakerStudioPortfolioPrincipalAssociation:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PrincipalARN: !Ref LaunchPrincipal
      PortfolioId: !Ref SageMakerStudioProductPortfolio
      PrincipalType: IAM


# Role used by Service Catalog to provision products
#####################################################  

  SageMakerProvisioningRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SageMakerProvisioningRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              Service:
                - servicecatalog.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: ProvisioningAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:UpdateStack
                Resource: arn:aws:cloudformation:*:*:stack/SC-*
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStacks
                  - cloudformation:GetTemplateSummary
                Resource: "*"
              - Effect: Allow
                Action:
                  - sagemaker:CreateDomain
                  - sagemaker:DescribeDomain
                  - sagemaker:DeleteDomain
                Resource: "*"         
              - Effect: Allow
                Action:                  
                  - s3:Get*
                Resource: "*"
                Condition:
                  StringEquals:
                    "s3:ExistingObjectTag/servicecatalog:provisioning": "true"
              - Effect: Allow
                Action:
                  - iam:AttachRolePolicy
                  - iam:CreateRole
                  - iam:CreatePolicy
                  - iam:DetachRolePolicy
                  - iam:PassRole
                  - iam:PutRolePolicy
                  - iam:Delete*
                  - iam:Get*
                  - iam:List*                  
                Resource: "*"

  SageMakerStudioPortfolioLaunchRoleConstraint:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    Properties:
      PortfolioId: !Ref SageMakerStudioProductPortfolio
      ProductId: !Ref SageMakerStudioProduct
      RoleArn: !GetAtt SageMakerProvisioningRole.Arn
      Description: Role used for provisioning
