Parameters:
  ImageName:
    Type: String
    Description: The name of the custom SageMaker image
  ECRImage:
    Type: String
    Description: Container image hosted in ECR

Resources:
  SageMakerCustomImage:
    Type: AWS::SageMaker::Image
    Properties:
      ImageDescription: Custom SageMaker Studio Image
      ImageName: !Ref ImageName
      ImageDisplayName: !Ref ImageName
      ImageRoleArn: !Join ["", ["arn:aws:iam::", !Ref AWS::AccountId, ":role/SageMakerExecutionRole"] ]

  SageMakerCustomImageVersion:
    Type: AWS::SageMaker::ImageVersion
    DependsOn: SageMakerCustomImage
    Properties:
      ImageName: !Ref ImageName
      BaseImage: !Ref ECRImage
